import type {
  Product,
  VendorProfile,
  Category,
  Service,
  Order,
  Commission,
  User,
  Review,
} from "@/types";

// ─── MOCK USERS ─────────────────────────────────────────────

export const mockUsers: User[] = [
  {
    id: "user-admin-1",
    email: "admin@kalavpp.com",
    name: "Kalavpp Admin",
    role: "ADMIN",
    avatar: "",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "user-vendor-1",
    email: "priya@kalavpp.com",
    name: "Priya Sharma",
    role: "VENDOR",
    bio: "Traditional Indian miniature artist with 15 years of experience",
    avatar: "",
    createdAt: "2025-02-01T00:00:00Z",
  },
  {
    id: "user-vendor-2",
    email: "arjun@kalavpp.com",
    name: "Arjun Mehta",
    role: "VENDOR",
    bio: "Contemporary sculptor and installation artist based in Mumbai",
    avatar: "",
    createdAt: "2025-02-15T00:00:00Z",
  },
  {
    id: "user-vendor-3",
    email: "kavya@kalavpp.com",
    name: "Kavya Nair",
    role: "VENDOR",
    bio: "Digital illustrator specializing in mythological narratives",
    avatar: "",
    createdAt: "2025-03-01T00:00:00Z",
  },
  {
    id: "user-customer-1",
    email: "customer@kalavpp.com",
    name: "Rahul Verma",
    role: "CUSTOMER",
    avatar: "",
    createdAt: "2025-03-10T00:00:00Z",
  },
];

// ─── MOCK VENDORS ───────────────────────────────────────────

export const mockVendors: VendorProfile[] = [
  {
    id: "vendor-1",
    userId: "user-vendor-1",
    storeName: "Priya's Miniatures",
    storeSlug: "priyas-miniatures",
    description:
      "Exquisite Rajasthani miniature paintings crafted using traditional pigments, gold leaf, and centuries-old techniques passed down through generations.",
    specializations: ["Miniature Painting", "Traditional Art", "Gold Leaf Work"],
    status: "APPROVED",
    rating: 4.8,
    totalSales: 245000,
    totalOrders: 89,
    user: mockUsers[1],
  },
  {
    id: "vendor-2",
    userId: "user-vendor-2",
    storeName: "Arjun Studio",
    storeSlug: "arjun-studio",
    description:
      "Contemporary sculptures that bridge the gap between traditional Indian craftsmanship and modern artistic expression.",
    specializations: ["Sculpture", "Installation Art", "Metal Work"],
    status: "APPROVED",
    rating: 4.6,
    totalSales: 580000,
    totalOrders: 42,
    user: mockUsers[2],
  },
  {
    id: "vendor-3",
    userId: "user-vendor-3",
    storeName: "Kavya Illustrations",
    storeSlug: "kavya-illustrations",
    description:
      "Vibrant digital illustrations rooted in Indian mythology and folklore, available as prints and digital downloads.",
    specializations: ["Digital Art", "Illustration", "Mythology"],
    status: "APPROVED",
    rating: 4.9,
    totalSales: 178000,
    totalOrders: 156,
    user: mockUsers[3],
  },
];

// ─── MOCK CATEGORIES ────────────────────────────────────────

export const mockCategories: Category[] = [
  {
    id: "cat-1",
    name: "Original Artworks",
    slug: "original-artworks",
    description: "One-of-a-kind original paintings and artworks",
    image: "/images/categories/original.jpg",
    _count: { products: 24 },
  },
  {
    id: "cat-2",
    name: "Prints & Reproductions",
    slug: "prints-reproductions",
    description: "High-quality art prints and reproductions",
    image: "/images/categories/prints.jpg",
    _count: { products: 56 },
  },
  {
    id: "cat-3",
    name: "Handcrafted Items",
    slug: "handcrafted-items",
    description: "Pottery, wood, metal, and textile creations",
    image: "/images/categories/handcrafted.jpg",
    _count: { products: 38 },
  },
  {
    id: "cat-4",
    name: "Digital Art",
    slug: "digital-art",
    description: "Digital paintings, illustrations, and design assets",
    image: "/images/categories/digital.jpg",
    _count: { products: 72 },
  },
  {
    id: "cat-5",
    name: "Traditional & Tribal Art",
    slug: "traditional-tribal",
    description: "Warli, Madhubani, Pattachitra, and more",
    image: "/images/categories/traditional.jpg",
    _count: { products: 31 },
  },
  {
    id: "cat-6",
    name: "Sculptures & Installations",
    slug: "sculptures-installations",
    description: "Three-dimensional art pieces and installations",
    image: "/images/categories/sculptures.jpg",
    _count: { products: 18 },
  },
  {
    id: "cat-7",
    name: "Art Merchandise",
    slug: "art-merchandise",
    description: "Art-inspired apparel, accessories, and home decor",
    image: "/images/categories/merchandise.jpg",
    _count: { products: 95 },
  },
  {
    id: "cat-8",
    name: "Art Books & Stationery",
    slug: "art-books-stationery",
    description: "Art books, sketchbooks, and premium stationery",
    image: "/images/categories/books.jpg",
    _count: { products: 27 },
  },
];

// ─── MOCK PRODUCTS ──────────────────────────────────────────

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    vendorId: "vendor-1",
    categoryId: "cat-1",
    title: "Rajasthani Royal Procession",
    slug: "rajasthani-royal-procession",
    description:
      "A stunning miniature painting depicting a royal Rajasthani procession, meticulously crafted using natural pigments and 24-karat gold leaf on handmade wasli paper. This piece captures the grandeur of Mughal-era ceremonial traditions with extraordinary detail and vibrant color work.",
    shortDescription: "Miniature painting with gold leaf on wasli paper",
    type: "PHYSICAL",
    status: "ACTIVE",
    price: 45000,
    compareAtPrice: 55000,
    currency: "INR",
    images: [
      "https://images.unsplash.com/photo-1578301978693-85fa9fd0c499?w=800&q=80",
      "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&q=80",
    ],
    tags: ["miniature", "rajasthani", "gold leaf", "traditional"],
    featured: true,
    rating: 4.9,
    reviewCount: 12,
    viewCount: 450,
    stockQuantity: 1,
    medium: "Natural pigments & gold leaf on wasli paper",
    style: "Rajasthani Miniature",
    artDimensions: "30 x 24 cm",
    yearCreated: 2025,
    isOriginal: true,
    isActive: true,
    certificate: true,
    vendor: mockVendors[0],
    category: mockCategories[0],
    createdAt: "2025-06-15T00:00:00Z",
  },
  {
    id: "prod-2",
    vendorId: "vendor-2",
    categoryId: "cat-6",
    title: "Eternal Dance - Bronze Sculpture",
    slug: "eternal-dance-bronze-sculpture",
    description:
      "A contemporary bronze sculpture inspired by the Nataraja form, representing the cosmic dance of creation and destruction. Cast using the lost-wax method with a rich patina finish that develops character over time.",
    shortDescription: "Contemporary bronze sculpture, lost-wax casting",
    type: "PHYSICAL",
    status: "ACTIVE",
    price: 125000,
    currency: "INR",
    images: [
      "https://images.unsplash.com/photo-1544413660-299165566b1d?w=800&q=80",
      "https://images.unsplash.com/photo-1561839561-b13bcfe95249?w=800&q=80",
    ],
    tags: ["sculpture", "bronze", "contemporary", "nataraja"],
    featured: true,
    rating: 4.7,
    reviewCount: 8,
    viewCount: 320,
    stockQuantity: 3,
    medium: "Bronze with patina finish",
    style: "Contemporary Indian",
    artDimensions: "45 x 30 x 25 cm",
    yearCreated: 2025,
    isOriginal: true,
    isActive: true,
    certificate: true,
    vendor: mockVendors[1],
    category: mockCategories[5],
    createdAt: "2025-07-01T00:00:00Z",
  },
  {
    id: "prod-3",
    vendorId: "vendor-3",
    categoryId: "cat-4",
    title: "Mythological Realms - Digital Art Pack",
    slug: "mythological-realms-digital-pack",
    description:
      "A collection of 12 high-resolution digital illustrations depicting scenes from Indian mythology. Each piece is rendered in vivid detail and available in multiple formats suitable for printing, digital display, and commercial use.",
    shortDescription: "12 high-res mythological digital illustrations",
    type: "DIGITAL",
    status: "ACTIVE",
    price: 2500,
    compareAtPrice: 4000,
    currency: "INR",
    images: [
      "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80",
      "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&q=80",
    ],
    tags: ["digital", "mythology", "illustration", "pack"],
    featured: true,
    rating: 4.8,
    reviewCount: 45,
    viewCount: 1200,
    isOriginal: false,
    isActive: true,
    certificate: false,
    vendor: mockVendors[2],
    category: mockCategories[3],
    createdAt: "2025-08-01T00:00:00Z",
  },
  {
    id: "prod-4",
    vendorId: "vendor-1",
    categoryId: "cat-5",
    title: "Madhubani Tree of Life",
    slug: "madhubani-tree-of-life",
    description:
      "A vibrant Madhubani painting depicting the sacred Tree of Life, created using traditional techniques from the Mithila region of Bihar. Painted with natural dyes on handmade paper using distinctive line work and fill patterns.",
    shortDescription: "Traditional Madhubani painting on handmade paper",
    type: "PHYSICAL",
    status: "ACTIVE",
    price: 18000,
    currency: "INR",
    images: [
      "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?w=800&q=80",
    ],
    tags: ["madhubani", "traditional", "tribal", "tree of life"],
    featured: false,
    rating: 4.6,
    reviewCount: 7,
    viewCount: 210,
    stockQuantity: 2,
    medium: "Natural dyes on handmade paper",
    style: "Madhubani / Mithila",
    artDimensions: "60 x 45 cm",
    yearCreated: 2025,
    isOriginal: true,
    isActive: true,
    certificate: true,
    vendor: mockVendors[0],
    category: mockCategories[4],
    createdAt: "2025-05-20T00:00:00Z",
  },
  {
    id: "prod-5",
    vendorId: "vendor-3",
    categoryId: "cat-7",
    title: "Ganesha Art Print Tote Bag",
    slug: "ganesha-art-print-tote-bag",
    description:
      "Premium organic cotton tote bag featuring an original Ganesha illustration. Screen-printed with eco-friendly inks. Sturdy construction with reinforced handles, perfect for art lovers who value sustainability.",
    shortDescription: "Organic cotton tote with Ganesha illustration",
    type: "MERCHANDISE",
    status: "ACTIVE",
    price: 799,
    currency: "INR",
    images: [
      "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80",
    ],
    tags: ["tote bag", "merchandise", "ganesha", "eco-friendly"],
    featured: false,
    rating: 4.4,
    reviewCount: 23,
    viewCount: 580,
    stockQuantity: 50,
    isOriginal: false,
    isActive: true,
    certificate: false,
    vendor: mockVendors[2],
    category: mockCategories[6],
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "prod-6",
    vendorId: "vendor-2",
    categoryId: "cat-3",
    title: "Terracotta Horse Set",
    slug: "terracotta-horse-set",
    description:
      "A set of hand-sculpted terracotta horses inspired by the Bankura Horse tradition of West Bengal. Each piece is unique, shaped by hand and fired in a traditional kiln. The set of three horses in graduating sizes makes a striking decorative ensemble.",
    shortDescription: "Hand-sculpted Bankura-style terracotta horses",
    type: "PHYSICAL",
    status: "ACTIVE",
    price: 8500,
    currency: "INR",
    images: [
      "https://images.unsplash.com/photo-1490312278390-ab64016e0aa9?w=800&q=80",
    ],
    tags: ["terracotta", "handcrafted", "bankura", "sculpture"],
    featured: true,
    rating: 4.5,
    reviewCount: 15,
    viewCount: 340,
    stockQuantity: 8,
    medium: "Terracotta",
    style: "Bankura Traditional",
    artDimensions: "15-30 cm height",
    isOriginal: false,
    isActive: true,
    certificate: false,
    vendor: mockVendors[1],
    category: mockCategories[2],
    createdAt: "2025-04-10T00:00:00Z",
  },
  {
    id: "prod-7",
    vendorId: "vendor-3",
    categoryId: "cat-4",
    title: "Brush Pack - Watercolor Dreams",
    slug: "brush-pack-watercolor-dreams",
    description:
      "A professional-grade digital brush pack for Procreate and Photoshop, featuring 48 custom brushes that mimic traditional Indian watercolor techniques. Includes wash brushes, detail brushes, texture brushes, and splatter effects.",
    shortDescription: "48 custom watercolor digital brushes",
    type: "DIGITAL",
    status: "ACTIVE",
    price: 1200,
    compareAtPrice: 1800,
    currency: "INR",
    images: [
      "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80",
    ],
    tags: ["digital", "brushes", "procreate", "photoshop", "watercolor"],
    featured: false,
    rating: 4.7,
    reviewCount: 67,
    viewCount: 2100,
    isOriginal: false,
    isActive: true,
    certificate: false,
    vendor: mockVendors[2],
    category: mockCategories[3],
    createdAt: "2025-07-15T00:00:00Z",
  },
  {
    id: "prod-8",
    vendorId: "vendor-1",
    categoryId: "cat-2",
    title: "Mughal Garden - Limited Edition Print",
    slug: "mughal-garden-limited-edition-print",
    description:
      "A museum-quality giclée print of the original Mughal Garden miniature painting, reproduced on archival cotton rag paper with pigment inks. Limited edition of 50 signed and numbered prints, each accompanied by a certificate of authenticity.",
    shortDescription: "Limited edition giclée print, signed & numbered",
    type: "PHYSICAL",
    status: "ACTIVE",
    price: 6500,
    currency: "INR",
    images: [
      "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&q=80",
    ],
    tags: ["print", "limited edition", "mughal", "giclée"],
    featured: true,
    rating: 4.8,
    reviewCount: 19,
    viewCount: 430,
    stockQuantity: 23,
    medium: "Giclée print on archival paper",
    style: "Mughal Miniature Reproduction",
    artDimensions: "40 x 30 cm",
    isOriginal: false,
    isActive: true,
    certificate: false,
    vendor: mockVendors[0],
    category: mockCategories[1],
    createdAt: "2025-08-20T00:00:00Z",
  },
];

// ─── MOCK SERVICES ──────────────────────────────────────────

export const mockServices: Service[] = [
  {
    id: "svc-1",
    vendorId: "vendor-1",
    title: "Custom Miniature Portrait",
    slug: "custom-miniature-portrait",
    description:
      "Commission a personalized miniature portrait painted in the traditional Rajasthani style. Using natural pigments and gold leaf on wasli paper, each portrait captures the subject with extraordinary detail and timeless elegance.",
    type: "PORTRAIT",
    basePrice: 35000,
    startingPrice: 35000,
    currency: "INR",
    deliveryDays: 45,
    maxRevisions: 3,
    images: [
      "https://images.unsplash.com/photo-1578301978693-85fa9fd0c499?w=800&q=80",
    ],
    tags: ["miniature", "portrait", "rajasthani", "gold leaf"],
    rating: 4.9,
    reviewCount: 12,
    isActive: true,
    vendor: mockVendors[0],
  },
  {
    id: "svc-2",
    vendorId: "vendor-2",
    title: "Custom Bronze Sculpture",
    slug: "custom-bronze-sculpture",
    description:
      "Commission a bespoke bronze sculpture for your space. From concept to finished piece, we collaborate closely to bring your vision to life using traditional lost-wax casting techniques with contemporary sensibilities.",
    type: "SCULPTURE",
    basePrice: 150000,
    startingPrice: 150000,
    currency: "INR",
    deliveryDays: 90,
    maxRevisions: 2,
    images: [
      "https://images.unsplash.com/photo-1544413660-299165566b1d?w=800&q=80",
    ],
    tags: ["bronze", "sculpture", "lost-wax", "bespoke"],
    rating: 4.8,
    reviewCount: 8,
    isActive: true,
    vendor: mockVendors[1],
  },
  {
    id: "svc-3",
    vendorId: "vendor-3",
    title: "Digital Portrait Illustration",
    slug: "digital-portrait-illustration",
    description:
      "Get a stunning digital portrait illustration in a mythological art style. Perfect for profile pictures, gifts, or personal branding. Includes multiple revisions and delivery in various digital formats.",
    type: "PORTRAIT",
    basePrice: 5000,
    startingPrice: 5000,
    currency: "INR",
    deliveryDays: 14,
    maxRevisions: 5,
    images: [
      "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80",
    ],
    tags: ["digital", "portrait", "illustration", "mythological"],
    rating: 4.7,
    reviewCount: 23,
    isActive: true,
    vendor: mockVendors[2],
  },
  {
    id: "svc-4",
    vendorId: "vendor-2",
    title: "Mural Installation",
    slug: "mural-installation",
    description:
      "Transform your space with a custom mural installation. We handle everything from concept design to on-site painting. Suitable for residences, offices, hotels, restaurants, and public spaces.",
    type: "MURAL",
    basePrice: 75000,
    startingPrice: 75000,
    currency: "INR",
    deliveryDays: 30,
    maxRevisions: 2,
    images: [
      "https://images.unsplash.com/photo-1561839561-b13bcfe95249?w=800&q=80",
    ],
    tags: ["mural", "wall art", "installation", "large scale"],
    rating: 4.9,
    reviewCount: 6,
    isActive: true,
    vendor: mockVendors[1],
  },
  {
    id: "svc-5",
    vendorId: "vendor-1",
    title: "Calligraphy Nameplate",
    slug: "calligraphy-nameplate",
    description:
      "Handcrafted calligraphy nameplates in traditional scripts including Devanagari, Urdu, and decorative English. Each nameplate is created on selected wood or brass with meticulous attention to letterform and ornamentation.",
    type: "CALLIGRAPHY",
    basePrice: 4500,
    startingPrice: 4500,
    currency: "INR",
    deliveryDays: 21,
    maxRevisions: 2,
    images: [
      "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?w=800&q=80",
    ],
    tags: ["calligraphy", "nameplate", "devanagari", "brass"],
    rating: 4.6,
    reviewCount: 15,
    isActive: true,
    vendor: mockVendors[0],
  },
  {
    id: "svc-6",
    vendorId: "vendor-3",
    title: "Brand Identity Design",
    slug: "brand-identity-design",
    description:
      "Complete brand identity design package for art-focused businesses. Includes logo design, color palette, typography selection, business cards, and brand guidelines document, all with an artistic sensibility.",
    type: "BRANDING",
    basePrice: 25000,
    startingPrice: 25000,
    currency: "INR",
    deliveryDays: 21,
    maxRevisions: 3,
    images: [
      "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&q=80",
    ],
    tags: ["branding", "logo", "identity", "design"],
    rating: 4.8,
    reviewCount: 19,
    isActive: true,
    vendor: mockVendors[2],
  },
];

// ─── MOCK ORDERS ────────────────────────────────────────────

export const mockOrders: Order[] = [
  {
    id: "order-1",
    orderNumber: "KV-3F8G2K-A1B2",
    userId: "user-customer-1",
    subtotal: 45000,
    shippingCost: 500,
    tax: 8190,
    total: 53690,
    currency: "INR",
    status: "DELIVERED",
    paymentStatus: "PAID",
    paymentMethod: "UPI",
    items: [
      {
        id: "oi-1",
        orderId: "order-1",
        productId: "prod-1",
        title: "Rajasthani Royal Procession",
        price: 45000,
        quantity: 1,
        type: "PHYSICAL",
        status: "DELIVERED",
      },
    ],
    createdAt: "2025-10-15T10:30:00Z",
  },
  {
    id: "order-2",
    orderNumber: "KV-4H9J3L-C3D4",
    userId: "user-customer-1",
    subtotal: 2500,
    shippingCost: 0,
    tax: 450,
    total: 2950,
    currency: "INR",
    status: "CONFIRMED",
    paymentStatus: "PAID",
    paymentMethod: "Card",
    items: [
      {
        id: "oi-2",
        orderId: "order-2",
        productId: "prod-3",
        title: "Mythological Realms - Digital Art Pack",
        price: 2500,
        quantity: 1,
        type: "DIGITAL",
        status: "CONFIRMED",
      },
    ],
    createdAt: "2025-11-02T14:15:00Z",
  },
  {
    id: "order-3",
    orderNumber: "KV-5K1M4N-E5F6",
    userId: "user-customer-1",
    subtotal: 9299,
    shippingCost: 200,
    tax: 1710,
    total: 11209,
    currency: "INR",
    status: "PROCESSING",
    paymentStatus: "PAID",
    paymentMethod: "UPI",
    items: [
      {
        id: "oi-3",
        orderId: "order-3",
        productId: "prod-5",
        title: "Ganesha Art Print Tote Bag",
        price: 799,
        quantity: 1,
        type: "MERCHANDISE",
        status: "PROCESSING",
      },
      {
        id: "oi-4",
        orderId: "order-3",
        productId: "prod-6",
        title: "Terracotta Horse Set",
        price: 8500,
        quantity: 1,
        type: "PHYSICAL",
        status: "PROCESSING",
      },
    ],
    createdAt: "2025-12-20T09:45:00Z",
  },
];

// ─── MOCK COMMISSIONS ───────────────────────────────────────

export const mockCommissions: Commission[] = [
  {
    id: "comm-1",
    customerId: "user-customer-1",
    vendorId: "vendor-1",
    serviceId: "svc-1",
    title: "Family Portrait in Miniature Style",
    description:
      "A family portrait of four members painted in traditional Rajasthani miniature style, with gold leaf accents.",
    budget: 50000,
    status: "IN_PROGRESS",
    deadline: "2026-03-15T00:00:00Z",
    createdAt: "2026-01-10T00:00:00Z",
    vendor: mockVendors[0],
    service: mockServices[0],
  },
  {
    id: "comm-2",
    customerId: "user-customer-1",
    vendorId: "vendor-3",
    serviceId: "svc-3",
    title: "Digital Avatar Illustration",
    description:
      "A mythological-style digital portrait for use as professional profile picture across platforms.",
    budget: 7000,
    status: "COMPLETED",
    deadline: "2026-01-20T00:00:00Z",
    createdAt: "2025-12-28T00:00:00Z",
    vendor: mockVendors[2],
    service: mockServices[2],
  },
];

// ─── MOCK REVIEWS ───────────────────────────────────────────

export const mockReviews: Review[] = [
  {
    id: "rev-1",
    userId: "user-customer-1",
    productId: "prod-1",
    rating: 5,
    title: "Absolutely breathtaking",
    comment:
      "The level of detail in this miniature painting is extraordinary. The gold leaf work catches light beautifully. A true masterpiece for our living room.",
    images: [],
    isVerified: true,
    createdAt: "2025-11-01T00:00:00Z",
    user: mockUsers[4],
  },
  {
    id: "rev-2",
    userId: "user-customer-1",
    productId: "prod-3",
    rating: 5,
    title: "Stunning digital work",
    comment:
      "The illustrations are incredibly detailed and the resolution is perfect for large prints. Great value for the quality.",
    images: [],
    isVerified: true,
    createdAt: "2025-11-10T00:00:00Z",
    user: mockUsers[4],
  },
];
